#!/bin/bash
FILE=memoria.out
make
if test -f "./bin/$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 --track-origins=yes ./bin/$FILE cfg/MEMORIA_CONFIG
fi
