#!/bin/bash
FILE=cpu.out
make
if test -f "./bin/$FILE"; then
    valgrind --tool=memcheck --leak-check=full --show-possibly-lost=no --show-reachable=no --num-callers=20 --track-origins=yes --log-file="logs/valgrind.log" ./bin/$FILE cfg/SUSPE_CONFIG
fi
