#ifndef TYPES_IDENTIFICADOR_OPERACION_H
#define TYPES_IDENTIFICADOR_OPERACION_H

typedef enum identificador_operacion
{
	CREAR_PROCESO,
    INICIALIZAR_PROCESO,
    FINALIZAR_PROCESO,
    SUSPENDER_PROCESO,
    HANDSHAKE_INFO_TRADUCCION,
    LEER_DATO,
    ESCRIBIR_DATO,
    OBTENER_NUMERO_TABLA_2_PARA_ENTRADA_TABLA_1,
    OBTENER_MARCO_PARA_ENTRADA_TABLA_2
} identificador_operacion;

#endif
