#ifndef TYPES_IDENTIFICADOR_OPERACION_H
#define TYPES_IDENTIFICADOR_OPERACION_H

typedef enum identificador_operacion
{
    CREAR_PROCESO,
    INICIALIZAR_PROCESO,
    FINALIZAR_PROCESO,
    SUSPENDER_PROCESO,
    BLOQUEAR_PROCESO,
    EJECUTAR_PROCESO,
    HANDSHAKE_INFO_TRADUCCION,
    LEER_DATO,
    ESCRIBIR_DATO,
    OBTENER_NUMERO_TABLA_2_PARA_ENTRADA_TABLA_1,
    OBTENER_MARCO_PARA_ENTRADA_TABLA_2,
    HANDSHAKE_SOY_KERNEL
} identificador_operacion;

char *identificador_operacion_to_string(identificador_operacion id_op);

#endif
